using Asp.Versioning;
using Asp.Versioning.ApiExplorer;
using LSE.Application.DI;
using LSE.Infrastructure.DI;
using LSE.StocksAPI.CustomMiddleware;
using LSE.StocksAPI.Realtime;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.RateLimiting;
using Microsoft.IdentityModel.Tokens;
using Microsoft.OpenApi.Models;
using Serilog;
using System.Text;

public partial class Program
{
    private static void Main(string[] args)
    {
        var builder = WebApplication.CreateBuilder(args);

        builder.Host.UseSerilog((ctx, lc) =>
            lc.ReadFrom.Configuration(ctx.Configuration));

        builder.Services.AddControllers();

        #region CORS – Allow cross-origin access from browser clients
        // Required to let the HTML frontend send requests to API & SignalR hub
        builder.Services.AddCors(options =>
        {
            options.AddPolicy("AllowAll", policy =>
                policy.SetIsOriginAllowed(_ => true)
                      .AllowAnyHeader()
                      .AllowAnyMethod()
                      .AllowCredentials());
        });
        #endregion


        #region SignalR – Real-time trade notifications to all connected brokers
         
        builder.Services.AddSignalR();
        #endregion


        #region API Versioning – Support versioned controllers like /api/v1/*
        builder.Services
            .AddApiVersioning(options =>
            {
                options.DefaultApiVersion = new ApiVersion(1, 0);
                options.AssumeDefaultVersionWhenUnspecified = true;
                options.ReportApiVersions = true;      
                options.ApiVersionReader = ApiVersionReader.Combine(
                    new UrlSegmentApiVersionReader(),      
                    new HeaderApiVersionReader("X-Api-Version"),
                    new QueryStringApiVersionReader("api-version")
                );
            })
            .AddApiExplorer(options =>
            {
                options.GroupNameFormat = "'v'V";         
                options.SubstituteApiVersionInUrl = true;
            });
        #endregion


        #region JWT Authentication – Validate tokens returned by BrokerLogin
        // Enables [Authorize] to protect trade actions and stock data
        builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
            .AddJwtBearer(options =>
            {
                options.TokenValidationParameters = new TokenValidationParameters
                {
                    ValidateIssuer = true,
                    ValidateAudience = true,
                    ValidateLifetime = true,
                    ValidateIssuerSigningKey = true,
                    ValidIssuer = builder.Configuration["Jwt:Issuer"],
                    ValidAudience = builder.Configuration["Jwt:Audience"],
                    IssuerSigningKey = new SymmetricSecurityKey(
                        Encoding.UTF8.GetBytes(builder.Configuration["Jwt:Key"]))
                };
            });
        #endregion


        #region MediatR – Dispatch commands & events (published from Application)
        // Loaded AFTER AddSignalR so handlers can receive IHubContext<TradesHub>
        builder.Services.AddMediatR(cfg =>
            cfg.RegisterServicesFromAssemblyContaining<TradeExecutedEventHandler>());
        #endregion


        #region Swagger – Interactive API UI including JWT authorization
        builder.Services.AddEndpointsApiExplorer();
        builder.Services.AddSwaggerGen(c =>
        {
            c.SwaggerDoc("v1", new OpenApiInfo
            {
                Title = "London Stock Exchange API",
                Version = "v1"
            });

            var securityScheme = new OpenApiSecurityScheme
            {
                Name = "Authorization",
                Type = SecuritySchemeType.Http,
                Scheme = "bearer",
                BearerFormat = "JWT",
                In = ParameterLocation.Header,
                Description = "Paste your token from BrokerLogin (without Bearer prefix)",
                Reference = new OpenApiReference
                {
                    Type = ReferenceType.SecurityScheme,
                    Id = "Bearer"
                }
            };

            c.AddSecurityDefinition("Bearer", securityScheme);
            c.AddSecurityRequirement(new OpenApiSecurityRequirement
            {
                { securityScheme, Array.Empty<string>() }
            });

            // XML comments generated by <GenerateDocumentationFile>true</...> in csproj
            var xmlFile = $"{System.Reflection.Assembly.GetExecutingAssembly().GetName().Name}.xml";
            var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);
            c.IncludeXmlComments(xmlPath, includeControllerXmlComments: true);
        });
        #endregion


        #region Dependency Injection – Register repositories, UoW, Db contexts, etc.
        builder.Services.AddApplicationServices();
        builder.Services.AddInfrastructureServices(builder.Configuration);
        #endregion


        #region Rate Limiting – Prevent request spam
        builder.Services.AddRateLimiter(options =>
        {
            options.AddFixedWindowLimiter("fixed", o =>
            {
                o.Window = TimeSpan.FromSeconds(10);
                o.PermitLimit = 20;       // max 20 requests per 10 seconds per client
            });
        });
        #endregion


        var app = builder.Build();
        app.Logger.LogInformation("LSE Stocks API is running...");

        #region Swagger UI – Only load UI in Development
        if (app.Environment.IsDevelopment())
        {
            app.UseSwagger();
            app.UseSwaggerUI(options =>
            {
                var provider = app.Services.GetRequiredService<IApiVersionDescriptionProvider>();
                foreach (var desc in provider.ApiVersionDescriptions)
                {
                    options.SwaggerEndpoint($"/swagger/{desc.GroupName}/swagger.json",
                        $"LSE API {desc.GroupName.ToUpper()}");
                }
            });
        }
        #endregion


        #region Middleware Pipeline – Request processing order 
        app.UseCors("AllowAll");
        app.UseHttpsRedirection();

        app.MapHub<TradesHub>("/realtime/trades");   // SignalR endpoint for browser live updates

        app.UseRateLimiter();

        //Custom API error response and validation response
        app.UseMiddleware<GlobalExceptionMiddleware>();   

        app.UseAuthentication();
        app.UseAuthorization();
        #endregion
          
        app.MapControllers();
        app.MapGet("/", () => "LSE Stocks API is running");

        app.Run();
    }
}
